### ISSUE TITLE
Privacy Proof for DP Logistic Regression

### ISSUE THREAD

**Issue by NicolaasWeideman** [IBM/differential-privacy-library#10]
It appears as though the differentially private logistic regression algorithm differs slightly from the algorithm it is based on, proposed in the [paper](https://arxiv.org/pdf/0912.0071.pdf) by Chaudhuri, Monteleoni and Sarwate.

Are the two algorithms equivalent? If not, is there a proof that shows the adapted algorithm is still differentially private?

**Comment by naoise-h** [comment]
Hi Nicolaas,

Thanks for your question. You're right that we had to make a few adjustments to Chaudhuri et al's algorithm. This was primarily for two reasons:
1. In order to generalise the algorithm to allow for a user-specified l2 norm of the data (the algorithm in the paper specifies a norm of 1); and,
2. In order to make it fit with the syntax of Scikit-learn's native Logistic Regression model.

Here is what we did to address the above points:
1. __Non-unity norms:__ The change to non-unity norms can be determined by looking at the proof of Theorem 2. Everything in the proof holds until you get to the line `|\lambda_1(E) + \lambda_2(E)| \le 2c`. If our new data norm is `q` (named [`data_sensitivity` in our code](https://github.com/IBM/differential-privacy-library/blob/0.1.2/diffprivlib/mechanisms/vector.py#L154)), then we get `|\lambda_1(E) + \lambda_2(E) \le 2 c q`. This leads to the [`data_sensitivity` term in the local `delta` variable](https://github.com/IBM/differential-privacy-library/blob/0.1.2/diffprivlib/mechanisms/vector.py#L213) (not to be confused with the `\delta` of differential privacy).
Later in the proof, we get `\|b - b'\| \le 2 q`, which requires us to change the exp term in the next equation to `exp{-\epsilon'_p \|b\| / (2 q)}`, which results in us [changing the scale variable in the Vector mechanism](https://github.com/IBM/differential-privacy-library/blob/0.1.2/diffprivlib/mechanisms/vector.py#L217). 

2. __Sklearn syntax:__ The objective functions employed in the paper (equation (1)) and by scikit-learn ([maths formula (for l2 regularisation)](https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression) and [code](https://github.com/scikit-learn/scikit-learn/blob/0.22/sklearn/linear_model/_logistic.py#L124)) are different. In order to rewrite equation (1) to match the form of scikit-learn, we must multiply across the objective by `n`, and divide the regulariser by 2, therefore `\Lambda = 1 / (2 n C)`. However, in practice the [code uses `alpha = 1 / C`](https://github.com/scikit-learn/scikit-learn/blob/0.22/sklearn/linear_model/_logistic.py#L966), giving `\Lambda = alpha / (2 n)`.
In our code, the `c / (n \Lambda)` of Algorithm 2 [becomes `c / (alpha / 2)`](https://github.com/IBM/differential-privacy-library/blob/0.1.2/diffprivlib/mechanisms/vector.py#L208) (with the added `data_sensitivity` term from 1. above).

All these changes ensures that we can match the behaviour of the non-private Sklearn version, while also being general enough for a wide range of use cases. Let me know if you have any other queries.
