### ISSUE TITLE
Why bounded laplace is not used for all libraries?

### ISSUE THREAD

**Issue by aitsam12** [IBM/differential-privacy-library#33]
I have gone through the paper (very nice research, congratulations), however, I still have two questions.

I can understand that the variance must be non-negative by principle and therefore you apply the Bounded Laplace.
But, what I do not get is that you show the problem in an example with the count in Mars (cool haha), and then you only focus on using Bounded Lap for the variance.

Why do you not use Bounded Laplace for all your queries in your library? Because all the queries can have <0 zero even though it does not make sense.

With respect to the count_non_zero:

I imagine your library functions implemented in a lambda function in AWS, and a user would use it e.g. to get a count. Why limit the user to count only > 0 values?
Your function does not output an array, right? Then the user would not be able to do "array.size"; for that matter, in line with your logic, a user can also use "array.mean" in numpy.

Thank you again for your time and consideration.

**Comment by naoise-h** [comment]
Hi Aitsam,

The reason for this is that using the bounded Laplace mechanism requires greater noise variance to satisfy differential privacy than truncating the naive Laplace mechanism. Therefore, we only use the bounded Laplace mechanism where the truncated mechanism may produce qualitiatively different results. For example, we use bounded Laplace when calculating the variance of a vector, because zero variance is qualitatively different from small (but non-zero) variance.

As for `count_non_zero` etc, we draw a distinction between functions that can be applied on an array (i.e. `count_non_zero`, `mean`, etc) and the [array interface](https://numpy.org/doc/stable/reference/arrays.interface.html) itself. Unfortunately, even hiding the data of an array from a user in Python is not do-able with the code alone, so this may be a moot point in the short-term anyway.
