### ISSUE TITLE
Array index out of bounds in https://github.com/IBM/differential-privacy-library/blob/main/diffprivlib/tools/quantiles.py#L134

### ISSUE THREAD

**Issue by justanotherlad** [IBM/differential-privacy-library#49]
#48 
However, in that case, `len(probabilties)=len(array)-1` .

That still means, if `rand` becomes greater than all `self._probabilities` in line 169 of https://github.com/IBM/differential-privacy-library/blob/eeae0d776eb9915732b4a30bdc02448ac26cb578/diffprivlib/mechanisms/exponential.py#L169, i.e, when `idx = len(self._probabilities)` as of line 174 of the same as per given conditions, line 134 of https://github.com/IBM/differential-privacy-library/blob/main/diffprivlib/tools/quantiles.py#L134 should still give an "array index out of bounds error" due to `array[idx+1]` reference, right, since `idx=len(probabilities)` and  `len(probabilties)=len(array)-1`, which means `array[idx+1] = array[len(array)]` ?

**Comment by naoise-h** [comment]
From the following, there are `k+1` probabilities (indexed from `0` through `k`) in the mechanism:

https://github.com/IBM/differential-privacy-library/blob/eeae0d776eb9915732b4a30bdc02448ac26cb578/diffprivlib/tools/quantiles.py#L131

So the outputs from this exponential mechanism will be in the range `[0, k]`, inclusive. This is okay, since `array` now has `k+2` entries, indexed from `0` through `k+1`, so `array[idx+1]` will always be valid:

https://github.com/IBM/differential-privacy-library/blob/eeae0d776eb9915732b4a30bdc02448ac26cb578/diffprivlib/tools/quantiles.py#L134

**Comment by justanotherlad** [comment]
But https://github.com/IBM/differential-privacy-library/blob/eeae0d776eb9915732b4a30bdc02448ac26cb578/diffprivlib/mechanisms/exponential.py#L174 states that `idx` is `k+1` in the worst case, not `k`, if I'm not wrong?

**Comment by naoise-h** [comment]
Ah yes, good spot! We'll get that fixed. That should be `idx = len(self._probabilities) - 1`.

Thanks!

**Comment by justanotherlad** [comment]
#50 Sent a PR for the same!
